sudo: false
dist: trusty

language: elixir

elixir:
  - 1.4

otp_release: 18.3

matrix:
  include:
    - elixir: 1.4
      otp_release: 19.2

env:
  - MIX_ENV=test

script: mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
